apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: columbus
  namespace: columbus
spec:
  replicas: 1
  selector:
    matchLabels:
      name: columbus
  strategy:
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
    type: RollingUpdate
  template:
    metadata:
      labels:
        name: columbus
    spec:
      containers:
      - args:
        - npm
        - start
        image: <image_name>
        imagePullPolicy: Always
        name: columbus
        ports:
        - containerPort: 3000
          protocol: TCP
