apiVersion: v1
kind: Service
metadata:
  labels:
    name: columbus
  name: columbus
  namespace: columbus
spec:
  ports:
  - port: 3000
    protocol: TCP
    targetPort: 3000
  selector:
    name: columbus
  type: LoadBalancer
